title: Antoine Broyelle
description: Personnal blog

url: https://antoinebrl.github.io/
baseurl: ""
paginate_path: blog/page:num/
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

social:
  github: antoinebrl
  twitter: antbrl
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com

sass:
  style: compressed

# google_analytics: "UA-58263416-1"
