title: Antoine Broyelle
description: Antoine Broyelle - Personnal blog

url: https://antoinebrl.github.io/
baseurl: ""
paginate_path: blog/page:num/
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

# includes_dir:
#  - "_includes"
#  - "_external"

navigation:
  - title: Home
    url: /index.html
  - title: Data visualization
    url: /dataviz/index.html
#  - title: Contact
#    url: /contact

collections:
  dataviz:
    output: true
    permalink: /:collection/:path/
  external:
    output: true
    # permalink: /:collection/:path/



social:
  github: antoinebrl
  twitter: antbrl
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com

sass:
  style: compressed

# google_analytics: "UA-58263416-1"

defaults:
  - scope:
      path: "p"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "dataviz"
    values:
      layout: "dataviz"
