name: Build and deploy Jekyll site to GitHub Pages + Update README.md with latest blog posts

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          JEKYLL_ENV: production
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
  
  update-readme:
    needs: github-pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: |
          echo '<link rel="stylesheet" type="text/css" media="all" href="https://antoinebrl.github.io/css/style.css"/>' > README.md
          sleep 60
          curl https://antoinebrl.github.io/ | awk 'f{if ($0=="</div>") exit; print} $0=="   <div class=\"content\">"{f=1}' | tr -d '\n' | sed 's/> *</></g' | sed 's/<a class="post-link" href="\//<a href="https\:\/\/antoinebrl.github.io\//g' >> README.md
          echo '</div></div>' >> README.md
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
